name: go-mod-tidy
on:
  workflow_call:
    inputs:
      go-version:
        required: false
        type: string
      go-version-file:
        required: false
        type: string
      aqua_version:
        required: true
        type: string
      working_directory:
        required: false
        type: string
      skip_push:
        type: boolean
        required: false
        default: false
    secrets:
      gh_token:
        required: false
      gh_app_id:
        required: false
      gh_app_private_key:
        required: false

jobs:
  go-mod-tidy:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions:
      contents: read # For checkout private repository
    steps:
      - run: |
          echo "::error:: Either go-version or go-version-file must be set."
          exit 1
        if: inputs.go-version == '' && inputs.go-version-file == ''
      - name: Checkout HEAD
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{github.event.pull_request.head.sha}}
          persist-credentials: false
      - name: Set up Go
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version: ${{inputs.go-version}}
          go-version-file: ${{inputs.go-version-file}}
          cache: true
      - name: Issue a GitHub Access Token
        uses: suzuki-shunsuke/github-token-action@350d7506222e3a0016491abe85b5c4dd475b67d1 # v0.2.1
        id: token
        if: "! inputs.skip_push && ! github.event.pull_request.head.repo.fork"
        with:
          github_token: ${{secrets.gh_token}}
          github_app_id: ${{secrets.gh_app_id}}
          github_app_private_key: ${{secrets.gh_app_private_key}}
      - name: Install int128/ghcp
        uses: aquaproj/aqua-installer@f13c5d2f0357708d85477aabe50fd3f725528745 # v3.1.0
        if: "! inputs.skip_push && ! github.event.pull_request.head.repo.fork"
        with:
          aqua_version: ${{inputs.aqua_version}}
          working_directory: ${{inputs.working_directory}}
        env:
          GITHUB_TOKEN: ${{steps.token.outputs.token}}

      - name: go mod tidy
        uses: suzuki-shunsuke/go-mod-tidy-action@67d43e82d9b5b3280b7082052dce18b77649476c # v0.1.1
        if: "! inputs.skip_push && ! github.event.pull_request.head.repo.fork"
        with:
          github_token: ${{steps.token.outputs.token}}
          working_directory: ${{inputs.working_directory}}

      - name: go mod tidy
        uses: suzuki-shunsuke/go-mod-tidy-action@67d43e82d9b5b3280b7082052dce18b77649476c # v0.1.1
        if: inputs.skip_push || github.event.pull_request.head.repo.fork
        with:
          skip_push: true
          working_directory: ${{inputs.working_directory}}
