name: go-mod-tidy
on:
  workflow_call:
    inputs:
      go-version:
        required: true
        type: string
      aqua_version:
        required: true
        type: string
      working_directory:
        required: false
        type: string
      skip_push:
        type: boolean
        required: false
        default: false
    secrets:
      gh_token:
        required: false
      gh_app_id:
        required: false
      gh_app_private_key:
        required: false

jobs:
  go-mod-tidy:
    runs-on: ubuntu-latest
    permissions:
      contents: read # For checkout private repository
    steps:
      - name: Checkout HEAD
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
        with:
          ref: ${{github.event.pull_request.head.sha}}
      - name: Set up Go
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
        with:
          go-version: ${{inputs.go-version}}
          cache: true
      - name: Issue a GitHub Access Token
        uses: suzuki-shunsuke/github-token-action@a058de0a42e494414cf4c112436d663a06fd16c0 # v0.1.0
        id: token
        with:
          github_token: ${{secrets.gh_token}}
          github_app_id: ${{secrets.gh_app_id}}
          github_app_private_key: ${{secrets.gh_app_private_key}}
      - name: Install int128/ghcp
        uses: aquaproj/aqua-installer@61e2563dfe7674cbf74fe6ec212e444198a3bb00 # v2.0.2
        with:
          aqua_version: ${{inputs.aqua_version}}
          working_directory: ${{inputs.working_directory}}
        env:
          GITHUB_TOKEN: ${{steps.token.outputs.token}}

      - name: go mod tidy
        uses: suzuki-shunsuke/go-mod-tidy-action@67d43e82d9b5b3280b7082052dce18b77649476c # v0.1.1
        with:
          github_token: ${{steps.token.outputs.token}}
          skip_push: ${{inputs.skip_push}}
          working_directory: ${{inputs.working_directory}}
