name: go-mod-tidy
on:
  workflow_call:
    inputs:
      go-version:
        required: true
        type: string
      aqua_version:
        required: true
        type: string
      working_directory:
        required: false
        type: string
      skip_push:
        type: boolean
        required: false
        default: false
    secrets:
      gh_token:
        required: false
      gh_app_id:
        required: false
      gh_app_private_key:
        required: false

jobs:
  go-mod-tidy:
    runs-on: ubuntu-latest
    permissions:
      contents: read # For checkout private repository
    steps:
      - name: Checkout HEAD
        uses: actions/checkout@v3.3.0
        with:
          ref: ${{github.event.pull_request.head.sha}}
      - name: Set up Go
        uses: actions/setup-go@v3.5.0
        with:
          go-version: ${{inputs.go-version}}
      - name: Issue a GitHub Access Token
        uses: suzuki-shunsuke/github-token-action@v0.1.0
        id: token
        with:
          github_token: ${{secrets.gh_token}}
          github_app_id: ${{secrets.gh_app_id}}
          github_app_private_key: ${{secrets.gh_app_private_key}}
      - name: Install int128/ghcp
        uses: aquaproj/aqua-installer@v2.0.2
        with:
          aqua_version: ${{inputs.aqua_version}}
          working_directory: ${{inputs.working_directory}}
        env:
          GITHUB_TOKEN: ${{steps.token.outputs.token}}

      - name: go mod tidy
        uses: suzuki-shunsuke/go-mod-tidy-action@v0.1.0
        with:
          github_token: ${{steps.token.outputs.token}}
          skip_push: ${{inputs.skip_push}}
          working_directory: ${{inputs.working_directory}}
