name: go-mod-tidy
on:
  workflow_call:
    inputs:
      go-version:
        required: true
        type: string
      aqua_version:
        required: true
        type: string
      working_directory:
        required: false
        type: string
      skip_push:
        type: boolean
        required: false
        default: false
    secrets:
      gh_token:
        required: false
      gh_app_id:
        required: false
      gh_app_private_key:
        required: false

jobs:
  go-mod-tidy:
    runs-on: ubuntu-latest
    permissions:
      contents: read # For checkout private repository
    steps:
      - name: Checkout HEAD
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          ref: ${{github.event.pull_request.head.sha}}
      - name: Set up Go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version: ${{inputs.go-version}}
          cache: true
      - name: Issue a GitHub Access Token
        uses: suzuki-shunsuke/github-token-action@350d7506222e3a0016491abe85b5c4dd475b67d1 # v0.2.1
        id: token
        if: "! inputs.skip_push && ! github.event.pull_request.head.repo.fork"
        with:
          github_token: ${{secrets.gh_token}}
          github_app_id: ${{secrets.gh_app_id}}
          github_app_private_key: ${{secrets.gh_app_private_key}}
      - name: Install int128/ghcp
        uses: aquaproj/aqua-installer@6ce1f8848ec8e61f14d57bd5d7597057a6dd187c # v3.0.1
        if: "! inputs.skip_push && ! github.event.pull_request.head.repo.fork"
        with:
          aqua_version: ${{inputs.aqua_version}}
          working_directory: ${{inputs.working_directory}}
        env:
          GITHUB_TOKEN: ${{steps.token.outputs.token}}

      - name: go mod tidy
        uses: suzuki-shunsuke/go-mod-tidy-action@67d43e82d9b5b3280b7082052dce18b77649476c # v0.1.1
        if: "! inputs.skip_push && ! github.event.pull_request.head.repo.fork"
        with:
          github_token: ${{steps.token.outputs.token}}
          working_directory: ${{inputs.working_directory}}

      - name: go mod tidy
        uses: suzuki-shunsuke/go-mod-tidy-action@67d43e82d9b5b3280b7082052dce18b77649476c # v0.1.1
        if: inputs.skip_push || github.event.pull_request.head.repo.fork
        with:
          skip_push: true
          working_directory: ${{inputs.working_directory}}
